# Copyright 2025 Jiaqi Liu. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: 'Documentation CI/CD'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
    name: Deploy Docs to GitHub Pages
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build with mkdocs-material via Docker
        run: 'build/build-docs.sh'
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          user_name: QubitPi
          user_email: jack20220723@gmail.com
          cname: cadvisor.qubitpi.org
